### ISSUE TITLE
New id on course restore

### ISSUE THREAD

**Issue by neeesn** [moodleuulm/moodle-local_sandbox#2]
Hi, 

We are using your plugin and it works like a dream, but there is one thing - when the restore is run, it restores the course with a new id, so extern link to the sandbox course breaks after each restore.
Is there any possible way to get the plugin to restore in same id, or is there some settings somewhere i have overlooked.

Thanks for a great plugin

**Comment by abias** [comment]
Hi,

this is the way the plugin works - it completely deletes the course and creates a new one (which thereby gets a  new id).

If the problem are just external links to the course which get broken when sandbox runs, you can circumvent the by using a link like https://<YOURMOODLE>/course/view.php?name=<COURSE-SHORTNAME> instead of https://<YOURMOODLE>/course/view.php?id=<COURSE-ID>

I think I will put that hint in the README file of the plugin in the next release.

Thanks,
Alex

**Comment by joelschmid91** [comment]
Hello @abias 

The feature @neesn mentioned would be interesting for us as well, if the plugin would restore the course as an existing one; keeping the current course id. Do you think there is a chance that this feature get's implemented? Especially if the sandbox plugin is running on a productive moodle platform and gets restored on a regular basis (once an hour).

Thanks in advance for your feedback!

Cheers, Joël

**Comment by abias** [comment]
Hi @joelschmid91,

thanks for your message.

@neeesn had the problem that he wanted to link to the course and this link broke after the run of the sandbox plugin. I provided a workaround for that case.
Do you have the same problem or what's the use case for keeping the same course IDs?

I don't say that it wouldn't be possible to keep the course IDs with the sandbox plugin, but I want to say that the decision of deleting the existing course and creating a new one was made several years ago and was done for some good reasons, especially to get exactly the same course without having to fiddle with deleting all existing data from the existing course. 

The only downside with this approach that I can see is that course IDs grow quite big if you really run sandbox every hour. And even that shouldn't be a problem in the long run as the Moodle course table is configured to hold 9.999.999.999 courses (https://github.com/moodle/moodle/blob/master/lib/db/install.xml#L72) which means that you could reset a course every hour for 1.141.552 years before Moodle runs out of course IDs.

Thanks,
Alex

**Comment by joelschmid91** [comment]
Hello @abias @neeesn 

We extended your plugin so a new setting can be set to keep the course id if desired. See following repo: https://git.ffhs.ch/joel.schmid/local_sandbox

Maybe you would like to include this in your official plugin?

Cheers, Joël

**Comment by abias** [comment]
Hi @joelschmid91,

that's nice to know, thanks for the heads-up. If it is possible for you to prepare a pull request, I will be happy to review it for our next major release.

Thanks,
Alex

**Comment by joelschmid91** [comment]
hello @abias 

Done, I hope I did it the right way. https://github.com/moodleuulm/moodle-local_sandbox/pull/4

Cheers, Joël

**Comment by abias** [comment]
Hi Joël,

thank you for your proposal and sorry for not responding to your issue earlier.

I will review the pull request finally for the upcoming release for Moodle 3.4.

Thanks,
Alex

**Comment by abias** [comment]
Integrated into master with https://github.com/moodleuulm/moodle-local_sandbox/commit/12fa4245d37f9077f8a293d2c5e63617803a60ce

**Comment by adpe** [comment]
Hello @abias @neeesn 

Thanks a lot @abias, the plugin works like a charm on Moodle 3.5. I tested it on both ways, with keeping the course id and without.

I've just a little question. Why do you change the handling of the provided backup files? Its easier to upload it for you by GUI than access over SCP? Or it's a security risk thing?

Thanks to integrate our changes to your repo. 🙌

**Comment by abias** [comment]
Hi @adpe ,

> Thanks a lot @abias, the plugin works like a charm on Moodle 3.5. I tested it on both ways, with keeping the course id and without.

Great to hear that :)

> I've just a little question. Why do you change the handling of the provided backup files? Its easier to upload it for you by GUI than access over SCP? Or it's a security risk thing?

I think you mean the change from storing the course backup files in a filearea instead of fetching them from Moodledata which came with the 3.4 version?
This change is not related to this ticket, but I think I can answer it quickly: When the plugin was peer reviewed for the very first time by Moodle HQ (for Moodle version _2.4_), I was told that asking admins to put files into Moodledata manually is bad practice because there are hosted installations out there where admins don't have direct access to Moodledata. Unfortunately, it took me 5 years to fix this request. Shame on me. But that's the main and only reason.

> Thanks to integrate our changes to your repo. 🙌

You're welcome.

Cheers,
Alex
