### ISSUE TITLE
Replace deprecated function "generate_uuid"

### ISSUE THREAD

**Issue by adpe** [moodleuulm/moodle-local_sandbox#7]
Running this plugin on Moodle 3.9 alpha code will raise following warning:
```php
++ generate_uuid() is deprecated. Please use \core\uuid::generate() instead. ++
* line 638 of /lib/setuplib.php: call to debugging()
* line 138 of /local/sandbox/classes/task/restore_courses.php: call to generate_uuid()
* line 248 of /lib/cronlib.php: call to local_sandbox\task\restore_courses->execute()
* line 150 of /admin/cli/scheduled_task.php: call to cron_run_inner_scheduled_task()
```

HTH,
Adrian

**Comment by Kathrin84** [comment]
Hello @adpe ,

thank you very much for raising this issue and pointing to this deprecated function. I think we would have missed this, because Behat did not fail yet as the function is only deprecated an not removed yet.
So I changed this quickly: https://github.com/moodleuulm/moodle-local_sandbox/commit/959834493a662d20b7f60c3c617f8b455c3d8dc5

Because this is fixed, I will close this issue.

Thanks again and best, Kathrin :)
